name: build and publish

on:
  workflow_call:
    inputs:
      dotnet-project-path:
        description: "Path to the .NET project file"
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.dotnet-project-path }}

      - name: Build and Publish BackgroundService
        run: dotnet publish ${{ inputs.dotnet-project-path }} -c Release -r win-x64 -p:OutputType=exe -p:PublishSingleFile=true -p:PlatformTarget=x64 --self-contained true
