name: CI/CD
on:
  pull_request:
    branches:
    - "*"
    types: [ opened, reopened, closed, synchronize ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      run-kubernetes-ci: ${{ steps.changes.outputs.pallet == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-workflows-ci: ${{ steps.changes.outputs.workflows == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-terraform-ci: ${{ steps.changes.outputs.terraform == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-solution-ci: ${{ steps.changes.outputs.solution == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-solution-cd: ${{ steps.changes.outputs.solution == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        list-files: json
        filters: |
          pallet:
            - '.pallet/**'
          workflows: 
            - '.github/workflows/**'
            - 'docker-compose.yaml'
            - 'devtools/**'
          terraform:
            - 'infrastructure/terraform/**'
          solution:
            - 'solutions/CN.Shared.JokeService/**' 

  build-and-publish:
    name: "Build and publish"
    needs: setup
    if: needs.setup.outputs.run-solution-ci == 'true'
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup wix
      run: dotnet tool install --global wix

    - name: Publish Worker
      run: dotnet publish solutions\CN.Shared.JokeService\JokeService\JokeService.csproj --self-contained true --runtime win-x64 --configuration Release --framework net8.0-windows -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishProtocol=FileSystem -p:PublishDir="bin\Release\net8.0-windows\win-x64\publish"

    - name: Build Installer
      run: dotnet build solutions\CN.Shared.JokeService\JokeService.Installer\JokeService.Installer.wixproj --configuration Release

  build-publish:
    name: "Build and publish"
    needs: setup
    if: needs.setup.outputs.run-solution-ci == 'true'
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup wix
      run: dotnet tool install --global wix

    - name: Publish Worker
      run: dotnet publish solutions\CN.Shared.JokeService\JokeService\JokeService.csproj --self-contained true --runtime win-x64 --configuration Release --framework net8.0-windows -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishProtocol=FileSystem -p:PublishDir="bin\Release\net8.0-windows\win-x64\publish"

    - name: Build Installer
      run: dotnet build solutions\CN.Shared.JokeService\JokeService.Installer\JokeService.Installer.wixproj --configuration Release

    - name: Move Installer to Staging
      shell: bash
      run: |
        mkdir -p infrastructure/terraform/scripts/installer/staging
        mv solutions\CN.Shared.JokeService\JokeService.Installer/bin/Release/JokeService.Installer.msi infrastructure/terraform/scripts/installer/staging

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto-pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.merge_commit_sha }}
        base: main
        title: Autogenerated - Publish Worker.exe to staging
        body: Files generated by merging ${{ github.event.pull_request.html_url }}
        commit-message: Publish Worker.exe

  checks-passed:
    name: Checks passed
    needs:
    - setup
    - build-and-publish
    - build-publish
    runs-on: ubuntu-latest
    if: always()
    steps:
    - run: exit 1
      name: "Catch errors"
      if: ${{ contains(join(needs.*.result, ','), 'failure') }}