name: CI/CD

on:
  pull_request:
    branches:
      - "*"
    types: [opened, reopened, closed, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      run-workflows-ci: ${{ steps.changes.outputs.workflows == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-terraform-ci: ${{ steps.changes.outputs.terraform == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-solution-ci: ${{ steps.changes.outputs.solution == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
      run-solution-cd: ${{ steps.changes.outputs.solution == 'true' && github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: json
          filters: |
            workflows:
              - '.github/workflows/**'
              - 'docker-compose.yaml'
              - 'devtools/**'
            terraform:
              - 'infrastructure/terraform/**'
            solution:
              - 'solutions/CN.Shared.JokeService/**'

  build-and-publish:
    name: Build and Publish
    needs: setup
    if: needs.setup.outputs.run-solution-ci == 'true'
    uses: ./.github/workflows/build-publish.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}

  build-publish-create-pr:
    name: Build, Publish, and Create PR
    needs: setup
    if: needs.setup.outputs.run-solution-cd == 'true'
    uses: ./.github/workflows/build-publish.yaml
    with:
      branch: main

  create-pr-and-close-old:
    name: Create PR and Close Old Autogenerated PRs
    needs: build-publish-create-pr
    uses: ./.github/workflows/create-pr.yaml

  checks-passed:
    name: Checks Passed
    needs:
      - setup
      - build-and-publish
      - build-publish-create-pr
      - create-pr-and-close-old
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: exit 1
        name: "Catch Errors"
        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
